package com.mesofi.mythclothapi.config;

import org.mapstruct.factory.Mappers;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

import com.mesofi.mythclothapi.figurineevents.FigurineEventMapper;
import com.mesofi.mythclothapi.figurines.mapper.FigurineMapper;

/** Test-only configuration that exposes MapStruct mapper beans used by service tests. */
@TestConfiguration
public class MapperTestConfig {

  /**
   * Creates the figurine mapper implementation generated by MapStruct.
   *
   * @return mapper for figurine entity and DTO conversions
   */
  @Bean
  FigurineMapper figurineMapper() {
    return Mappers.getMapper(FigurineMapper.class);
  }

  /**
   * Creates the figurine event mapper implementation generated by MapStruct.
   *
   * @return mapper for figurine event conversions
   */
  @Bean
  FigurineEventMapper figurineEventMapper() {
    return Mappers.getMapper(FigurineEventMapper.class);
  }
}
