package com.mesofi.mythclothapi.utils;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.List;

import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.crypto.MACSigner;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;

/**
 * Utility factory for creating JWT tokens used in tests.
 *
 * <p>This class provides helper methods to generate signed JSON Web Tokens (JWT) with predefined
 * claims, roles, and permissions. The generated tokens can be used to authenticate requests in unit
 * and integration tests.
 *
 * <p>The tokens generated by this factory are signed using the HMAC SHA-256 algorithm and a static
 * test secret key.
 */
public class TestJwtFactory {

  /**
   * Creates a JWT token representing an authenticated administrator user.
   *
   * <p>The generated token includes:
   *
   * <ul>
   *   <li>User identifier as the subject
   *   <li>Test username
   *   <li>ADMIN role
   *   <li>Catalog read, write, update, and delete permissions
   *   <li>API issuer information
   *   <li>Expiration date set one year from token creation
   * </ul>
   *
   * @return a serialized signed JWT token
   * @throws Exception if the JWT cannot be signed or serialized
   */
  public static String createAdminToken() throws Exception {

    String secret = "sbOHJ60mLNmUpSNiSYiHpR2IgM3kPTVsiAItguC4T7E=";

    JWTClaimsSet claims =
        new JWTClaimsSet.Builder()
            .subject("1")
            .claim("name", "Test User")
            .claim("roles", List.of("ADMIN"))
            .claim(
                "permissions",
                List.of("catalogs:read", "catalogs:write", "catalogs:update", "catalogs:delete"))
            .issuer("myth-cloth-api")
            .expirationTime(Date.from(Instant.now().plus(365, ChronoUnit.DAYS)))
            .build();

    SignedJWT jwt = new SignedJWT(new JWSHeader(JWSAlgorithm.HS256), claims);

    jwt.sign(new MACSigner(secret.getBytes()));

    return jwt.serialize();
  }
}
