management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

myth-cloth:
  security:
    jwt:
      issuer: "myth-cloth-api"
      ttl-minutes: 60

server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: myth-cloth-api
