logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO   # <- Shows SQL statements
    org.hibernate.orm.jdbc.bind: INFO   # <- Shows query parameters

myth-cloth:
  bootstrap:
    admin:
      FACEBOOK: ${FACEBOOK_BOOTSTRAP_ADMIN_PROVIDER}
      GOOGLE: ${GOOGLE_BOOTSTRAP_ADMIN_PROVIDER}
      LOCAL: ${DEMO_BOOTSTRAP_ADMIN_PROVIDER}

  demo:
    enabled: true
    provider-user-id: 00000
    name: "Demo Local"
    email: "demo.local@mythcollection.com"

  facebook:
    app-id: ${FACEBOOK_APP_ID:4393993617525351}
    app-secret: ${FACEBOOK_APP_SECRET}
    graph-url: https://graph.facebook.com/

  google:
    client-id: ${GOOGLE_CLIENT_ID:1068577777042-fmeugfjurp1nbbfqq4q544gjk2h2l3cb.apps.googleusercontent.com}

  import:
    drive-url: https://docs.google.com/spreadsheets/d/%s/export?format=csv
    file-id: 1TKlCnCAp2o3hjT35kgtVEXpDxkAplIA8HBBPx-kqKio

  security:
    jwt:
      secret: ${JWT_SECRET}
      # Use the following command to generate a new secret:  `openssl rand -base64 32`
    cors-urls:
      - "http://localhost:5173"

server:
  port: 9090

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mythclothlocal}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true   # <- Pretty-print SQL
        show_sql: false     # <- Log SQL to console
        use_sql_comments: false # <- Adds Hibernate comments to queries
        highlight_sql: true        # ANSI colors (Hibernate 6+)

  rabbitmq:
    port: 5672
    host: localhost
    username: mythcloth
    password: mythcloth
    virtual-host: /
    ssl:
      enabled: false

  sql:
    init:
      mode: always   # FORCE db/*.sql to run
      data-locations:
      - classpath:db/seed-catalogs.sql
      - classpath:db/seed-stores.sql
