logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO  # <- Shows query parameters
# Change the app-id and app-secret using new credentials. For now, the app-id and app-secret are for a test Facebook app. If you want to use your own Facebook app, you can create one at https://developers.facebook.com/apps/ and then update the app-id and app-secret here.
myth-cloth:
  bootstrap:
    admin:
      FACEBOOK: ${FACEBOOK_BOOTSTRAP_ADMIN_PROVIDER}
      GOOGLE: ${GOOGLE_BOOTSTRAP_ADMIN_PROVIDER}
      LOCAL: ${DEMO_BOOTSTRAP_ADMIN_PROVIDER}

  demo:
    enabled: ${DEMO_MODE:false}
    provider-user-id: 99999
    name: "Demo"
    email: "demo@mythcollection.com"

  facebook:
    app-id: ${FACEBOOK_APP_ID}
    app-secret: ${FACEBOOK_APP_SECRET}
    graph-url: https://graph.facebook.com/

  google:
    client-id: ${GOOGLE_CLIENT_ID}

  import:
    drive-url: https://docs.google.com/spreadsheets/d/%s/export?format=csv
    file-id: 1TKlCnCAp2o3hjT35kgtVEXpDxkAplIA8HBBPx-kqKio

  security:
    jwt:
      secret: ${JWT_SECRET}
      # Use the following command to generate a new secret:  `openssl rand -base64 32`
    cors-url: "https://myth-cloth-ui.onrender.com"

server:
  port: ${PORT:9090} # Uses Render's port, or defaults to 9090

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true   # <- Pretty-print SQL
        show_sql: false     # <- Log SQL to console
        use_sql_comments: false # <- Adds Hibernate comments to queries
        highlight_sql: false        # ANSI colors (Hibernate 6+)

  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  sql:
    init:
      mode: never   # Do not run db/*.sql on startup in production
      data-locations:
        - classpath:db/seed-catalogs.sql
        - classpath:db/seed-stores.sql
