logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO  # <- Shows query parameters

myth-cloth:
  facebook:
    app-id: "??"
    app-secret: "??"
    graph-url: https://graph.facebook.com/

  google:
    client-id: "??"

  security:
    jwt:
      secret: "BOGdxpyZM5GftkuYzhFyQYxSJR0Aoi5e17nhn+MWm84="
      # Use the following command to generate a new secret:  `openssl rand -base64 32`
    cors-url: "https://myth-cloth-ui.onrender.com"

server:
  port: ${PORT:9090} # Uses Render's port, or defaults to 9090

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true   # <- Pretty-print SQL
        show_sql: false     # <- Log SQL to console
        use_sql_comments: false # <- Adds Hibernate comments to queries

  sql:
    init:
      mode: never   # FORCE data.sql to run with 'always'
