logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO  # <- Shows query parameters
# Change the app-id and app-secret using new credentials. For now, the app-id and app-secret are for a test Facebook app. If you want to use your own Facebook app, you can create one at https://developers.facebook.com/apps/ and then update the app-id and app-secret here.
myth-cloth:
  facebook:
    app-id: "26792785000395793"
    app-secret: "c1ed86ac1d957f5fdb4fc6ba07d17478"
    graph-url: https://graph.facebook.com/

  google:
    client-id: 1068577777042-hv9euam7dtr72cl9rqdvbk822h4mhip5.apps.googleusercontent.com

  import:
    drive-url: https://docs.google.com/spreadsheets/d/%s/export?format=csv
    file-id: 1TKlCnCAp2o3hjT35kgtVEXpDxkAplIA8HBBPx-kqKio

  security:
    jwt:
      secret: "BOGdxpyZM5GftkuYzhFyQYxSJR0Aoi5e17nhn+MWm84="
      # Use the following command to generate a new secret:  `openssl rand -base64 32`
    cors-url: "https://myth-cloth-ui.onrender.com"

server:
  port: ${PORT:9090} # Uses Render's port, or defaults to 9090

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true   # <- Pretty-print SQL
        show_sql: false     # <- Log SQL to console
        use_sql_comments: false # <- Adds Hibernate comments to queries
        highlight_sql: false        # ANSI colors (Hibernate 6+)

  sql:
    init:
      mode: never   # FORCE data.sql to run with 'always'
