logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: TRACE   # <- Shows query parameters

myth-cloth:
  demo:
    enabled: false
    provider-user-id: 11111
    name: "Demo Integration"
    email: "demo.integration@mythcollection.com"

  facebook:
    app-id: "0000"
    app-secret: "1111"

  security:
    jwt:
      secret: "WWOAnyRkezhKw5xeoCJZ1J/0+qy6I7azOjt19SlfC4M="
      # Use the following command to generate a new secret:  `openssl rand -base64 32`
    cors-url: "http://localhost:5173"

spring:
  rabbitmq:
    host: localhost
    username: intg-mythcloth
    password: intg-mythcloth

  sql:
    init:
      mode: never   # FORCE data.sql to run with 'always'
