SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE public.role_permission RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.roles RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;