SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE public.series RESTART IDENTITY;
TRUNCATE TABLE public.groups RESTART IDENTITY;
TRUNCATE TABLE public.distributions RESTART IDENTITY;
TRUNCATE TABLE public.lineups RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;