SET REFERENTIAL_INTEGRITY FALSE;

-- Security tables
TRUNCATE TABLE public.roles RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.role_permission RESTART IDENTITY;
-- Store tables
TRUNCATE TABLE public.stores RESTART IDENTITY;
TRUNCATE TABLE public.lineups RESTART IDENTITY;
TRUNCATE TABLE public.series RESTART IDENTITY;
TRUNCATE TABLE public.distributors RESTART IDENTITY;
TRUNCATE TABLE public.figurines RESTART IDENTITY;
TRUNCATE TABLE public.figurine_distributor RESTART IDENTITY;
TRUNCATE TABLE public.figurine_events RESTART IDENTITY;
TRUNCATE TABLE public.figurine_stores_unmatched RESTART IDENTITY;
TRUNCATE TABLE public.figurine_stores RESTART IDENTITY;
TRUNCATE TABLE public.figurine_store_pricings RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
