SET REFERENTIAL_INTEGRITY FALSE;

-- Security tables
TRUNCATE TABLE public.roles RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.role_permission RESTART IDENTITY;
-- Catalog tables
TRUNCATE TABLE public.series RESTART IDENTITY;
TRUNCATE TABLE public.groups RESTART IDENTITY;
TRUNCATE TABLE public.distributions RESTART IDENTITY;
TRUNCATE TABLE public.lineups RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
