SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE public.roles RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.role_permission RESTART IDENTITY;
TRUNCATE TABLE public.collectors RESTART IDENTITY;
TRUNCATE TABLE public.collector_providers RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;