SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE public.figurine_distributor RESTART IDENTITY;
TRUNCATE TABLE public.figurine_events RESTART IDENTITY;
TRUNCATE TABLE public.non_official_images RESTART IDENTITY;
TRUNCATE TABLE public.official_images RESTART IDENTITY;
TRUNCATE TABLE public.figurines RESTART IDENTITY;
TRUNCATE TABLE public.distributors RESTART IDENTITY;
TRUNCATE TABLE public.anniversaries RESTART IDENTITY;
TRUNCATE TABLE public.distributions RESTART IDENTITY;
TRUNCATE TABLE public.groups RESTART IDENTITY;
TRUNCATE TABLE public.lineups RESTART IDENTITY;
TRUNCATE TABLE public.series RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;