SET REFERENTIAL_INTEGRITY FALSE;

-- Security tables
TRUNCATE TABLE public.roles RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.role_permission RESTART IDENTITY;
-- Catalog tables
TRUNCATE TABLE public.distributors RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
