SET REFERENTIAL_INTEGRITY FALSE;

-- Security tables
TRUNCATE TABLE public.roles RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.role_permission RESTART IDENTITY;
-- Catalog tables
TRUNCATE TABLE public.lineups RESTART IDENTITY;
TRUNCATE TABLE public.series RESTART IDENTITY;
TRUNCATE TABLE public.groups RESTART IDENTITY;
TRUNCATE TABLE public.distributors RESTART IDENTITY;
TRUNCATE TABLE public.distributions RESTART IDENTITY;
TRUNCATE TABLE public.anniversaries RESTART IDENTITY;
-- Figurine tables
TRUNCATE TABLE public.figurine_distributor RESTART IDENTITY;
TRUNCATE TABLE public.figurine_events RESTART IDENTITY;
TRUNCATE TABLE public.figurine_imports RESTART IDENTITY;
TRUNCATE TABLE public.figurines RESTART IDENTITY;
TRUNCATE TABLE public.non_official_images RESTART IDENTITY;
TRUNCATE TABLE public.official_images RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
