SET REFERENTIAL_INTEGRITY FALSE;

-- Security tables
TRUNCATE TABLE public.roles RESTART IDENTITY;
TRUNCATE TABLE public.permissions RESTART IDENTITY;
TRUNCATE TABLE public.role_permission RESTART IDENTITY;
-- Collector tables
TRUNCATE TABLE public.distributors RESTART IDENTITY;
TRUNCATE TABLE public.collector_providers RESTART IDENTITY;
TRUNCATE TABLE public.collectors RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
